services:
  - type: web
    name: online-grocery
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app

    envVars:
      - key: MYSQL_HOST
        value: localhost
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: Pandiyarajan_21
      - key: MYSQL_DATABASE
        value: grocery_db
